### PR TITLE
Fix country report

### LINKED ISSUE #1873: Bugfix: Example Country report not rendering charts
## Expected Behavior
Charts currently not rendering and country count is wrong in summary text. 

## Current Behavior
See https://gilead-biostats.github.io/gsm/report_kri_country.html
image

## Steps to Reproduce

1.
2.
3.
4.

### LINKED ISSUE #1881: Bugfix: Group breakdown beneath Study Overview table should evaluate most recent snapshot.
## Expected Behavior
Number of groups with at least one red KRI, red or amber KRI, and neither red nor amber KRI should come from the most recent snapshot in the data.

## Current Behavior
Counts are across snapshots:

image

## Possible Solution
Filter results data on latest snapshot prior to counting.

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by samussiah**
## Overview
Issue caused on the js side of the group overview widget when a group subset of `"red"` is applied and there are no red flags.  Potentially an issue with `rbm-viz`, which currently errors out on empty input data...

## Test Notes/Sample Code
```
# Run country-level KRI report.
lChartsCountry <- MakeCharts(
  dfResults = reportingResults_country,
  dfGroups = reportingGroups_country,
  dfMetrics = reportingMetrics_country,
  dfBounds = reportingBounds_country
)

strOutputFile <- "StandardCountryReport.html"
kri_report_path <- Report_KRI(
  lCharts = lChartsCountry,
  dfResults = reportingResults_country,
  dfGroups = reportingGroups_country,
  dfMetrics = reportingMetrics_country,
  strOutputFile = strOutputFile
)
```

## Connected Issues
- Closes #1873 
- Closes #1881

### CODE REVIEW

**Comment by zdz2101** [comment]
image

we're so back

**Review by zdz2101 — APPROVED** [review]

**Review by lauramaxwell — APPROVED** [review]
nice catch! this makes sense, and it also partially addresses the issue of having an empty overview table when the report is opened.

**Review by lauramaxwell — DISMISSED** [review]
hmmm, actually there is still an issue with the overview text- it doesn't match the table, which shows one amber flag. 
image

**Comment by zdz2101** [comment]
image
LGTM

**Review by zdz2101 — APPROVED** [review]

**Pull request merged**
