### PR TITLE
Add `rbm-viz` v2.1.0.

### LINKED ISSUE #1855: Feature: merge in updated rbm-viz `index.js`
## Feature Details

Add in new widget features in `rbm-viz` to `gsm` for use in reporting

### LINKED ISSUE #1860: Feature: Group dropdown should trigger `riskSignalSelected` event.

### PR DESCRIPTION
**Pull request by samussiah**
## Overview
Adds new `riskSignalSelected` event that can be monitored by any ancestor of the widget (`barChart`, `scatterPlot`, `timeSeries`, `groupOverview`).  Returns the {gsm} data associated with the clicked risk signal.

The event also fires when the widget-level group dropdown changes.  For the time series, the event should return the latest data point.

## Test Notes/Sample Code
1. Generate a report.
```
load_all()
lCharts <- MakeCharts(
  dfResults = reportingResults,
  dfGroups = reportingGroups,
  dfMetrics = reportingMetrics,
  dfBounds = reportingBounds
)

strOutputFile <- "StandardSiteReport.html"
kri_report_path <- Report_KRI(
  lCharts = lCharts,
  dfResults = reportingResults,
  dfGroups = reportingGroups,
  dfMetrics = reportingMetrics,
  strOutputFile = strOutputFile
)
browseURL('StandardSiteReport.html')
```
2. Open the report in the browser.
3. Open the browser console and add an event listener for `riskSignalSelected`:
```
document.body.addEventListener('riskSignalSelected', (event) => {
    console.table(event.data);
});
```
4. Click a point/bar and verify the underlying result is displayed in the browser console.
5. Update the widget-level group dropdown and verify the underlying result is displayed in the browser console.
    - For the time series, verify the latest result is displayed in the browser console.

## Connected Issues
- Closes #1855 
- Closes #1860

### CODE REVIEW

**Review by jonthegeek — COMMENTED** [review]
This definitely looks interesting! For the moment it still makes sense for me to wrap my own version of the widget, but I'll definitely take a close look when this is merged to see what's left in my version that isn't over here, and whether it makes sense to add issues here (or in rbm-viz) to sync the versions.

**Comment by lauramaxwell** [comment]
@samussiah are you still working on this, or is it in draft by accident?

**Comment by samussiah** [comment]
> @samussiah are you still working on this, or is it in draft by accident?

@lauramaxwell - I'm waiting for feedback from the Gismo UI team. It sounds like this event will need to be triggered by the widget dropdowns as well.

It _might_ work for @jonthegeek's purposes with a dedicated event listener on the `{gsm.app}` side of things - love that idea!  Theoretically a single event listener could catch interactions in all widgets...

**Comment by jonthegeek** [comment]
> Theoretically a single event listener could catch interactions in all widgets...

I'm trying to keep things neatly namespaces, then recombine as makes sense. That way these could eventually work for selecting two sites to compare, for example.

**Review by lauramaxwell — APPROVED** [review]
working great, for me! feel free to merge, @samussiah

**Review by zdz2101 — APPROVED** [review]
Super cool!

**Pull request merged**
