### PR TITLE
Closes #1760 Updating dropdown menu for articles in website

### LINKED ISSUE #1760: QC: Update Articles dropdown in pkgdown header
## QC Details
Let's add an [`articles` section to `_pkgdown.yml`](https://pkgdown.r-lib.org/reference/build_articles.html#index-and-navbar)

- Include the following in the pkgdown header dropdown (others can be accessed via articles page): 
  - Data Model Overview (DataModel.rmd)
  - Analysis Pipeline Deep Dive (DataAnalysis.rmd)
  - Reporting Pipeline Deep Dive (DataReporting.rmd)
  - Cookbook (Cookbook.rmd)

### PR DESCRIPTION
**Pull request by zdz2101**
## Overview
- Preexisitng `fix-1760` branch had recommended code snippet in #1760, modified to ensure `articles/index.html` presents itself correctly
- Subheaders now in dropdown menu, needed to put text inside of `navbar` instead of "~"
- Article `KRI Method` needed to be renamed to achieve this

## Test Notes/Sample Code

Notes:

### CODE REVIEW

**Comment by zdz2101** [comment]
@lauramaxwell you mentioned something about some small css modifications for the yeti theme, do you know where to usually make this modification?

**Comment by lauramaxwell** [comment]
I think you can download the `yeti` css style file [here](https://bootswatch.com/yeti/), edit it and save it in `pkgdown/extra.css` in the package root. alternatively, we can use a theme like `lumen` that has similar colors, but better dropdown formatting

**Comment by lauramaxwell** [comment]
@zdz2101 i'll take a look at customizing the css for the dropdown this afternoon.

**Comment by lauramaxwell** [comment]
I added some css to make the dropdown headers more legible. Let me know what you think!

image

**Comment by zdz2101** [comment]
I think it looks great! I'll have to keep this in mind as a neat little trick

**Review by lauramaxwell — APPROVED** [review]
looks good!

**Pull request merged**
