### PR TITLE
Flag colors

### LINKED ISSUE #1879: Feature: Reduce render time of Flags Over Time module in report.
## Feature Details
With more and more snapshots the flags over time table takes a long time to render. Would be good to figure out how to speed up the process.

### LINKED ISSUE #1893: Feature: Include hidden GroupID in Report_MetricTable()
## Feature Details
It would be (very) helpful if Report_MetricTable()'s generated {gt} table kept the GroupID (separate from the cleaner thing used for display), and then used `gt::cols_hide()` to hide that value. That way I could use the value for clicks. In general, keep identifying information in our GT tables, but hide those columns if necessary.

### LINKED ISSUE #1895: Bugfix: Enrolled as number in Report_MetricTable()
## Expected Behavior
When I wrap `Report_MetricTable()` in a Shiny module and make it interactive, and sort by Enrolled, it should sort by that *number*.

## Current Behavior
It treats the number as text, and sorts accordingly. Thus "67" comes before "9", for example. The other columns sort as expected.

## Possible Solution
Cast Enrolled to an integer in `MakeMetricTable()`. (it comes in ass character because it's in dfGroups, and all the Value values are character)

## Steps to Reproduce

1.
2.
3.
4.

### LINKED ISSUE #1896: Bugfix: Background vs Foreground in Report_MetricTable()
## Expected Behavior
Flags are easy to see.

## Current Behavior
bg + flag color are too close together thus hard to see.

## Possible Solution
Standardize reports on transparent bg with muted/dark color in fg.

## Steps to Reproduce
```r
Report_MetricTable(
  dfResults = reportingResults %>%
    dplyr::filter(.data$MetricID == "kri0001") %>%
    FilterByLatestSnapshotDate(),
  dfGroups = reportingGroups
)
```

1. Run the code above.
2. Find 0X155
3. Note its flag:
  - The background should be transparent (for everything).
  - The icon should be colored by the flag.

### PR DESCRIPTION
**Pull request by jonthegeek**
## Overview
Fix output classes in `MakeMetricTable()`.
Update and standardize Report_MetricTable() and Report_FlagOverTime() coloration.

## Test Notes/Sample Code
```r
Report_FlagOverTime(
  reportingResults,
  reportingMetrics
)
```
```r
Report_MetricTable(
  dfResults = reportingResults %>%
    dplyr::filter(
      .data$MetricID == "kri0001"
    ) %>%
    FilterByLatestSnapshotDate(),
  dfGroups = reportingGroups
)
# For comparison
MakeMetricTable(
  dfResults = reportingResults %>%
    dplyr::filter(
      .data$MetricID == "kri0001"
    ) %>%
    FilterByLatestSnapshotDate(),
  dfGroups = reportingGroups
) %>% 
  tibble::as_tibble()
```

## Connected Issues

- Closes #1895.
- Closes #1896.
- Closes #1879.
- Closes #1893.

### CODE REVIEW

**Comment by zdz2101** [comment]
image

image


Phenomenal, much easier to see

**Review by zdz2101 — APPROVED** [review]
image

image


Phenomenal, much easier to see

**Review by lauramaxwell — APPROVED** [review]
looks great! i added a space between the charts and the next kri becuase it was overlapping 
image
now it looks like this: 
image

feel free to take a look, confirm and merge.

**Review by jonthegeek — COMMENTED** [review]
Looks good!

**Pull request merged**
