### PR TITLE
KRI Report generation

### LINKED ISSUE #1646: Feature: Add `strGroupLevel` param to `Input_Rate`
## Feature Details

`GroupLevel` in dfInput is currently set using the `strGroupCol` - this might be ok sometimes, but also want to be able to provide the `GroupLevel` directly via a new strGroupLevel parameter. 

Will want to update kri/cou workflows to add `strGroupLevel: GroupLevel` (which will be populated from `meta$GroupLevel` for calls to `Input_Rate`

cc: @samussiah

### PR DESCRIPTION
**Pull request by lauramaxwell**
## Overview

- Get site and country report running.
- Update examples
- Finalize various features. 

Fixes #1646 #1637 #1592 #1457  

Fixes 

## Test Notes/Sample Code
Known issues:
1. Need to look at `Report_*` functions to align on `dfSite`/`dfGroups` usage.
2. `SiteSelect` overall dropdown is not populating with sites
3. `StudyID` is not being passed through to report (currently looking for it in `dfStudy`)
4. Study Overview table column labels are off (see below) 
image

Ran the following to generate a report for KRI0001:
```
devtools::load_all()
# Load raw data and workflows
lRaw <- list(
    dfSUBJ = clindata::rawplus_dm,
    dfAE = clindata::rawplus_ae,
    dfPD = clindata::ctms_protdev,
    dfLB = clindata::rawplus_lb,
    dfSTUDCOMP = clindata::rawplus_studcomp,
    dfSDRGCOMP = clindata::rawplus_sdrgcomp %>% dplyr::filter(.data$phase == 'Blinded Study Drug Completion'),
    dfDATACHG = clindata::edc_data_points,
    dfDATAENT = clindata::edc_data_pages,
    dfQUERY = clindata::edc_queries,
    dfENROLL = clindata::rawplus_enroll
)

wf_mapping <- MakeWorkflowList(strNames = "mapping")
wf_kri <- MakeWorkflowList(strNames="kri0001")
wf_reporting <- MakeWorkflowList(strNames = "reporting")

# Generate Mapped Data
lMapped <- RunWorkflows(lWorkflow = wf_mapping, lData = lRaw)

# Generate Analysis Results Data
lAnalysis <- RunWorkflows(lWorkflow = wf_kri, lData = lMapped)

# Generate Reporting Data
lReporting_Input <- list(
    ctms_site = clindata::ctms_site,
    ctms_study = clindata::ctms_study,
    dfEnrolled =lMapped$dfEnrolled,
    lWorkflows = wf_kri,
    lAnalysis = list(kri0001 = lAnalysis),
    dSnapshotDate = Sys.Date(),
    strStudyID = "ABC-123"
)

lReporting <- RunWorkflows(lWorkflow = wf_reporting, lData = lReporting_Input)

# Convience Mappings
dfGroups <- lReporting$dfGroups
dfMetrics <- lReporting$dfMetrics
dfSummary <- lReporting$dfSummary
dfBounds <- lReporting$dfBounds

# Create dfSites and dfStudy pending rbm-viz update to use dfGroups
dfSite <- dfSites <- dfGroups %>%
  filter(GroupLevel == "Site") %>%
  pivot_wider(names_from=Param, values_from=Value) %>%
  rename(
    SiteID = GroupID,
    status = Status,
    enrolled_participants = ParticipantCount
  )

dfStudy <- dfStudies <- dfGroups %>% filter(GroupLevel == "Study") %>% pivot_wider(names_from=Param, values_from=Value)

# Lazy longitudinal data
dfSummary_long <- bind_rows(
  dfSummary %>% mutate(SnapshotDate = Sys.Date()),
  dfSummary %>% mutate(SnapshotDate = Sys.Date() - 1),
  dfSummary %>% mutate(SnapshotDate = Sys.Date() - 14)
)

#Create Charts for all metrics
options(vsc.viewer = FALSE)
metrics<- unique(dfMetrics$MetricID)
charts <- metrics %>% map(~Visualize_Metric(
  dfSummary = dfSummary_long,
  dfBounds = dfBounds,
  dfGroups = dfGroups,
  dfMetrics = dfMetrics,
  strMetricID = .x
)
) %>% setNames(metrics)

Report_KRI(lCharts = charts,
 dfSummary = dfSummary, 
dfStudy = dfStudy, 
dfSite = dfSite, 
dfMetrics = dfMetrics, 
strOutpath = "~/test.html")
```

Notes:

### CODE REVIEW

**Comment by jwildfire** [comment]
To do

- [ ] dfSummary -> dfResults in widget params
- [ ] Update dfGroupLevel to use `unique(dfMetrics$GroupLevel)` by default in Widget_GroupOverview

**Comment by jwildfire** [comment]
Site-level report is working for a single snapshot via `inst/examples/snapshot.R`. Remaining to do's below. Will get this ready to review/merge Monday, and we can file any needed issues. 

# To do

- [x] https://github.com/Gilead-BioStats/gsm/issues/1646 
- [ ] https://github.com/Gilead-BioStats/gsm/issues/1637 
- [x] https://github.com/Gilead-BioStats/gsm/issues/1592 
- [x] https://github.com/Gilead-BioStats/gsm/issues/1457
- [ ] dfSummary -> dfResults in widget params
- [ ] Update dfGroupLevel to use `unique(dfMetrics$GroupLevel)` by default in Widget_GroupOverview
- [ ] Fully remove DT requirement?
- [ ] Update/streamline/de-duplicate all `inst/example`
- [ ] Make test scripts/debug country-level and longitudinal reports
- [ ] Merge dev in to branch
- [ ] Merge in #1570 
- [ ] Fix (or maybe remove/refactor) global site filter
- [ ] Update examples for all widgets and report to use new sample data sets from #1629 .

**Comment by lauramaxwell** [comment]
@jwildfire I'm taking these three tasks from the list above this morning:
 - dfSummary -> dfResults in widget params
 - Update dfGroupLevel to use unique(dfMetrics$GroupLevel) by default in Widget_GroupOverview
 - Update examples for all widgets and report to use new sample data sets from https://github.com/Gilead-BioStats/gsm/pull/1629 .

**Comment by lauramaxwell** [comment]
@jonthegeek and @jwildfire it looks like `sampleResults` and `sampleSummary` have integer GroupID values, while they should be characters. this pops up when testing/making examples for `Report_MetricTable()`. going to fix this, unless I missed something at the end of last week. let me know!

**Comment by jwildfire** [comment]
> @jonthegeek and @jwildfire it looks like `sampleResults` and `sampleSummary` have integer GroupID values, while they should be characters. this pops up when testing/making examples for `Report_MetricTable()`. going to fix this, unless I missed something at the end of last week. let me know!

Agree it makes more sense for them to be character.

**Comment by jwildfire** [comment]
Sounds good, @lauramaxwell. I'm planning on working on example updates, including country-level and longitudinal reports before scrum. I'll work in a separate branch to avoid conflicts.

**Comment by jonthegeek** [comment]
They were auto-set to integer because the ones in the csv happen to all be integers. Definitely hard-code them to character in the construction script (and probably double-check all columns in all the sample data for similar issues)!

**Comment by lauramaxwell** [comment]
> (and probably double-check all columns in all the sample data for similar issues)!

yep! already did this in the script for the GroupIDs, but found that the dates are also stripped of their date class, so i'm going to go in and edit that in the construction script as well.

**Comment by jwildfire** [comment]
Updated widgets to get `inst/examples/snapshot.R` running again and filed issues to clean up remaining issues/

**Review by jwildfire — APPROVED** [review]

**Pull request merged**
